---
title: Event
slug: Glossary/event
tags:
  - CodingScripting
  - Glossary
---
<p>Events are assets generated by <a href="/en-US/docs/Glossary/DOM">DOM</a> elements, which can be manipulated by a Javascript code.</p>

<h2 id="see_also">See also</h2>

<ul>
 <li><a href="/en-US/docs/Web/API/Event">Event documentation on MDN</a></li>
 <li><a href="https://www.w3.org/TR/DOM-Level-2-Events/events.html">Official website</a></li>
 <li>{{Interwiki("wikipedia", "DOM Events")}} on Wikipedia</li>
</ul>
