version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
      exclude:
        - "@mdn/*"
    open-pull-requests-limit: 10
    groups:
      npm-prod:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
      npm-dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
    labels:
      - automated pr
      - dependencies
      - javascript
    commit-message:
      prefix: chore
      prefix-development: build
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 3
    labels:
      - automated pr
      - dependencies
      - github actions
    commit-message:
      prefix: ci
      include: scope
