Content:Accessibility:
  - '\/docs\/Web\/Accessibility'
Content:CSS:
  - '\/docs\/Web\/CSS'
Content:Events:
  - '\/docs\/Web\/Events'
Content:Firefox:
  - '\/docs\/Mozilla/Firefox'
Content:Games:
  - '\/docs\/Games'
Content:Glossary:
  - '\/docs\/Glossary'
Content:Guide:
  - '\/docs\/Web/Guide'
Content:HTML:
  - '\/docs\/Web\/HTML'
Content:HTTP:
  - '\/docs\/Web\/HTTP'
Content:JS:
  - '\/docs\/Web\/JavaScript'
Content:Learn:
  - '\/docs\/Learn_web_development\/'
Content:Manifest:
  - '\/docs\/Web\/Manifest'
Content:MathML:
  - '\/docs\/Web\/MathML'
Content:Media:
  - '\/docs\/Web\/Media'
Content:Meta:
  - '\/docs\/MDN'
Content:Performance:
  - '\/docs\/Web\/Performance'
Content:PWA:
  - '\/docs\/Web\/Progressive_web_apps'
Content:Security:
  - '\/docs\/Web\/Security'
Content:SVG:
  - '\/docs\/Web\/SVG'
Content:wasm:
  - '\/docs\/WebAssembly'
Content:WebAPI:
  - '\/docs\/Web\/API'
Content:WebDriver:
  - '\/docs\/Web\/WebDriver'
Content:WebExt:
  - '\/docs\/Mozilla\/Add-ons'
