--
--  Drop all tables.
--
DROP TABLE "PA_ACTIVATION" CASCADE CONSTRAINTS;
DROP TABLE "PA_ACTIVATION_HISTORY" CASCADE CONSTRAINTS;
DROP TABLE "PA_APPLICATION" CASCADE CONSTRAINTS;
DROP TABLE "PA_APPLICATION_VERSION" CASCADE CONSTRAINTS;
DROP TABLE "PA_TOKEN" CASCADE CONSTRAINTS;
DROP TABLE "PA_MASTER_KEYPAIR" CASCADE CONSTRAINTS;
DROP TABLE "PA_SIGNATURE_AUDIT" CASCADE CONSTRAINTS;
DROP TABLE "PA_INTEGRATION" CASCADE CONSTRAINTS;
DROP TABLE "PA_APPLICATION_CALLBACK" CASCADE CONSTRAINTS;
DROP TABLE "PA_RECOVERY_CODE" CASCADE CONSTRAINTS;
DROP TABLE "PA_RECOVERY_PUK" CASCADE CONSTRAINTS;
DROP TABLE "PA_RECOVERY_CONFIG" CASCADE CONSTRAINTS;
DROP TABLE "PA_OPERATION" CASCADE CONSTRAINTS;
DROP TABLE "PA_OPERATION_TEMPLATE" CASCADE CONSTRAINTS;

-- Optionally drop the shedlock table
-- DROP TABLE "shedlock" CASCADE CONSTRAINTS;

--
--  Drop all sequences.
--
DROP SEQUENCE "PA_APPLICATION_SEQ";
DROP SEQUENCE "PA_APPLICATION_VERSION_SEQ";
DROP SEQUENCE "PA_MASTER_KEYPAIR_SEQ";
DROP SEQUENCE "PA_SIGNATURE_AUDIT_SEQ";
DROP SEQUENCE "PA_ACTIVATION_HISTORY_SEQ";
DROP SEQUENCE "PA_RECOVERY_CODE_SEQ";
DROP SEQUENCE "PA_RECOVERY_PUK_SEQ";
DROP SEQUENCE "PA_RECOVERY_CONFIG_SEQ";
DROP SEQUENCE "PA_OPERATION_TEMPLATE_SEQ";
