---
title: RTCPeerConnection
slug: Web/API/RTCPeerConnection
tags:
  - API
  - Audio
  - Communication
  - Interface
  - Media
  - NeedsUpdate
  - Networking
  - RTCPeerConnection
  - Reference
  - Telecom
  - Video
  - WebRTC
  - WebRTC API
browser-compat: api.RTCPeerConnection
---
<p>{{APIRef('WebRTC')}}</p>

<p>The <strong><code>RTCPeerConnection</code></strong> interface represents a WebRTC connection between the local computer and a remote peer. It provides methods to connect to a remote peer, maintain and monitor the connection, and close the connection once it's no longer needed.</p>

<p>{{InheritanceDiagram}}</p>

<h2 id="Constructor">Constructor</h2>

<dl>
  <dt>{{DOMxRef("RTCPeerConnection.RTCPeerConnection", "RTCPeerConnection()")}}</dt>
  <dd>
    Returns a newly-created <code>RTCPeerConnection</code>,
    which represents a connection between the local device and a remote peer.
  </dd>
</dl>

<h2 id="Static_methods">Static methods</h2>

<dl>
  <dt>{{DOMxRef("RTCPeerConnection.generateCertificate", "generateCertificate()")}}</dt>
  <dd>
    Creates an X.509 certificate and its corresponding private key,
    returning a {{jsxref("Promise")}} that resolves with the new {{DOMxRef("RTCCertificate")}} once it is generated.
  </dd>
</dl>

<h2 id="Properties">Properties</h2>

<p><em>Also inherits properties from {{DOMxRef("EventTarget")}}.</em></p>

<dl>
  <dt>{{DOMxRef("RTCPeerConnection.canTrickleIceCandidates", "canTrickleIceCandidates")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns a boolean value which indicates whether or not
    the remote peer can accept <a href="https://datatracker.ietf.org/doc/html/draft-ietf-mmusic-trickle-ice">trickled ICE candidates</a>.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.connectionState", "connectionState")}} {{ReadOnlyInline}}</dt>
  <dd>
    Indicates the current state of the peer connection
    by returning one of the strings
    <code>new</code>, <code>connecting</code>, <code>connected</code>, <code>disconnected</code>,
    <code>failed</code>, or <code>closed</code>.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.currentLocalDescription", "currentLocalDescription")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns an {{DOMxRef("RTCSessionDescription")}} object describing
    the local end of the connection
    as it was most recently successfully negotiated
    since the last time
    this <code>RTCPeerConnection</code> finished negotiating and connecting to a remote peer.
    Also included is a list of any ICE candidates
    that may already have been generated by the ICE agent
    since the offer or answer represented by the description was first instantiated.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.currentRemoteDescription", "currentRemoteDescription")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns an {{DOMxRef("RTCSessionDescription")}} object describing
    the remote end of the connection
    as it was most recently successfully negotiated
    since the last time
    this <code>RTCPeerConnection</code> finished negotiating and connecting to a remote peer.
    Also included is a list of any ICE candidates
    that may already have been generated by the ICE agent
    since the offer or answer represented by the description was first instantiated.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.iceConnectionState", "iceConnectionState")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns a string which state of the ICE agent associated with this RTCPeerConnection.
    It can be one of the following values:
    <code>new</code>, <code>checking</code>, <code>connected</code>, <code>completed</code>,
    <code>failed</code>, <code>disconnected</code>, or <code>closed</code>.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.iceGatheringState", "iceGatheringState")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns a string
    that describes connection's ICE gathering state.
    This lets you detect, for example,
    when collection of ICE candidates has finished.
    Possible values are:
    <code>new</code>, <code>gathering</code>, or <code>complete</code>.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.localDescription", "localDescription")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns an {{DOMxRef("RTCSessionDescription")}}
    describing the session for the local end of the connection.
    If it has not yet been set, returns <code>null</code>.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.peerIdentity", "peerIdentity")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns a {{jsxref("Promise")}}
    that resolves to an {{DOMxRef("RTCIdentityAssertion")}}
    which contains a string
    identifying the remote peer.
    Once this promise resolves successfully,
    the resulting identity is the target peer identity
    and will not change for the duration of the connection.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.pendingLocalDescription", "pendingLocalDescription")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns an {{DOMxRef("RTCSessionDescription")}} object
    describing a pending configuration change for the local end of the connection.
    This does not describe the connection as it currently stands,
    but as it may exist in the near future.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.pendingRemoteDescription", "pendingRemoteDescription")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns an {{DOMxRef("RTCSessionDescription")}} object
    describing a pending configuration change for the remote end of the connection.
    This does not describe the connection as it currently stands,
    but as it may exist in the near future.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.remoteDescription", "remoteDescription")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns an {{DOMxRef("RTCSessionDescription")}} object
    describing the session,
    including configuration and media information,
    for the remote end of the connection.
    If this hasn't been set yet, this returns <code>null</code>.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.sctp", "sctp")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns an {{DOMxRef("RTCSctpTransport")}} object
    describing the {{Glossary("SCTP")}} transport layer
    over which SCTP data is being sent and received.
    If SCTP hasn't been negotiated, this value is <code>null</code>.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.signalingState", "signalingState")}} {{ReadOnlyInline}}</dt>
  <dd>
    Returns a string
    describing the state of the signaling process on the local end of the connection
    while connecting or reconnecting to another peer.
    It is one of the following values:
    <code>stable</code>, <code>have-local-offer</code>, <code>have-remote-offer</code>,
    <code>have-local-pranswer</code>, <code>have-remote-pranswer</code>, or <code>closed</code>.
  </dd>
</dl>

<h3 id="Event_handlers">Event handlers</h3>

<p><em>Also inherits event handlers from {{DOMxRef("EventTarget")}}.</em></p>

<dl>
  <dt>{{DOMxRef("RTCPeerConnection.onconnectionstatechange", "onconnectionstatechange")}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which is called to handle the {{DOMxRef("RTCPeerConnection/connectionstatechange_event", "connectionstatechange")}} event.
    This happens whenever the aggregate state of the connection changes.
    The aggregate state is a combination of the states of all of the individual network transports
    being used by the connection.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.ondatachannel", "ondatachannel")}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the {{DOMxRef("RTCPeerConnection/datachannel_event", "datachannel")}} event.
    This event, of type {{DOMxRef("RTCDataChannelEvent")}}, is sent
    when an {{DOMxRef("RTCDataChannel")}} is added to the connection
    by the remote peer calling {{DOMxRef("RTCPeerConnection.createDataChannel", "createDataChannel()")}}.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.onicecandidate", "onicecandidate")}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the {{DOMxRef("RTCPeerConnection/icecandidate_event", "icecandidate")}} event.
    This happens whenever the local {{Glossary("ICE")}} agent needs to deliver a message
    to the other peer through the signaling server.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.onicecandidateerror", "onicecandidateerror")}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the {{DOMxRef("RTCPeerConnection/icecandidateerror_event", "icecandidateerror")}} event.
    This event is fired when an error occurs during the {{Glossary("ICE")}} candidate gathering process.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.oniceconnectionstatechange", "oniceconnectionstatechange")}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the {{DOMxRef("RTCPeerConnection/iceconnectionstatechange_event", "iceconnectionstatechange")}} event.
    This happens whenever the local {{Glossary("ICE")}} agent needs to deliver a message
    to the other peer through the signaling server.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.onicegatheringstatechange", "onicegatheringstatechange")}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the {{DOMxRef("RTCPeerConnection/icegatheringstatechange_event", "icegatheringstatechange")}} event.
    This happens when the {{Glossary("ICE")}} gathering state changes.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.onnegotiationneeded", "onnegotiationneeded")}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the {{DOMxRef("RTCPeerConnection/negotiationneeded_event", "negotiationneeded")}} event.
    This event is fired
    when a change has occurred which requires session negotiation.
    This negotiation should be carried out as the offerer,
    because some session changes cannot be negotiated as the answerer.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.onsignalingstatechange", "onsignalingstatechange")}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the {{DOMxRef("RTCPeerConnection/signalingstatechange_event", "signalingstatechange")}} event.
    The function receives as input the event object of type {{DOMxRef("Event")}};
    this event is sent
    when the peer connection's {{DOMxRef("RTCPeerConnection.signalingState", "signalingState")}} changes,
    which may happen either because of a call to {{DOMxRef("RTCPeerConnection.setLocalDescription", "setLocalDescription()")}}
    or to {{DOMxRef("RTCPeerConnection.setRemoteDescription", "setRemoteDescription()")}}.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.ontrack", "ontrack")}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the {{DOMxRef("RTCPeerConnection/track_event", "track")}} event.
    The function receives as input the event object, of type {{DOMxRef("RTCTrackEvent")}};
    this event is sent
    when a new incoming {{DOMxRef("MediaStreamTrack")}} has been created
    and associated with an {{DOMxRef("RTCRtpReceiver")}} object
    which has been added to the set of receivers on the connection.
  </dd>
</dl>

<h3 id="Obsolete_properties">Obsolete properties</h3>

<dl>
  <dt>{{DOMxRef("RTCPeerConnection.onaddstream", "onaddstream")}} {{Obsolete_Inline}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the obsolete {{DOMxRef("RTCPeerConnection/addstream_event", "addstream")}} event.
  </dd>
  <dt>{{DOMxRef("RTCPeerConnection.onremovestream", "onremovestream")}} {{Obsolete_Inline}}</dt>
  <dd>
    Is an <a href="/en-US/docs/Web/Events/Event_handlers">event handler</a>
    which specifies a function
    which is called to handle the obsolete {{DOMxRef("RTCPeerConnection/removestream_event", "removestream")}} event.
  </dd>
</dl>

<h2 id="Methods">Methods</h2>

<p><em>Also inherits methods from {{DOMxRef("EventTarget")}}.</em></p>

<dl>
  <dt>{{DOMxRef("RTCPeerConnection.addIceCandidate", "addIceCandidate()")}}</dt>
  <dd>
    Adds a new remote candidate to the <code>RTCPeerConnection</code>'s remote description,
    which describes the state of the remote end of the connection.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.addTrack", "addTrack()")}}</dt>
  <dd>
    Adds a new {{DOMxRef("MediaStreamTrack")}}
    to the set of tracks
    which will be transmitted to the other peer.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.addTransceiver", "addTransceiver()")}}</dt>
  <dd>
    Creates a new {{DOMxRef("RTCRtpTransceiver")}}
    and adds it to the set of transceivers associated with the connection.
    Each transceiver represents a bidirectional stream,
    with both an {{DOMxRef("RTCRtpSender")}} and an {{DOMxRef("RTCRtpReceiver")}} associated with it.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.close", "close()")}}</dt>
  <dd>
    Closes the current peer connection.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.createAnswer", "createAnswer()")}}</dt>
  <dd>
    Initiates the creation an {{Glossary("SDP")}} answer
    to an offer received from a remote peer
    during the offer/answer negotiation of a WebRTC connection.
    The answer contains information
    about any media already attached to the session,
    codecs and options supported by the browser,
    and any {{Glossary("ICE")}} candidates already gathered.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.createDataChannel", "createDataChannel()")}}</dt>
  <dd>
    Initiates the creation a new channel linked with the remote peer,
    over which any kind of data may be transmitted.
    This can be useful for back-channel content,
    such as images, file transfer, text chat, game update packets, and so forth.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.createOffer", "createOffer()")}}</dt>
  <dd>
    Initiates the creation of an {{Glossary("SDP")}} offer
    for the purpose of starting a new WebRTC connection to a remote peer.
    The SDP offer includes information about any {{DOMxRef("MediaStreamTrack")}} objects
    already attached to the WebRTC session, codec, and options supported by the browser,
    as well as any candidates already gathered by the {{Glossary("ICE")}} agent,
    for the purpose of being sent over the signaling channel to a potential peer
    to request a connection or to update the configuration of an existing connection.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.getConfiguration", "getConfiguration()")}}</dt>
  <dd>
    Returns an {{DOMxRef("RTCConfiguration")}} object
    which indicates the current configuration of the connection.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.getIdentityAssertion", "getIdentityAssertion()")}}</dt>
  <dd>
    Initiates the gathering of an identity assertion
    and returns a {{jsxref("Promise")}}
    which resolves to an identity assertion encoded as a string.
    This has an effect only
    if {{DOMxRef("RTCPeerConnection.signalingState", "signalingState")}} is not <code>closed</code>.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.getReceivers", "getReceivers()")}}</dt>
  <dd>
    Returns an array of {{DOMxRef("RTCRtpReceiver")}} objects,
    each of which represents one {{Glossary("RTP")}} receiver.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.getSenders", "getSenders()")}}</dt>
  <dd>
    Returns an array of {{DOMxRef("RTCRtpSender")}} objects,
    each of which represents the {{Glossary("RTP")}} sender
    responsible for transmitting one track's data.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.getStats", "getStats()")}}</dt>
  <dd>
    Returns a {{jsxref("Promise")}}
    which resolves with data providing statistics
    about either the overall connection
    or about the specified {{DOMxRef("MediaStreamTrack")}}.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.getTransceivers", "getTransceivers()")}}</dt>
  <dd>
    Returns a list of all the {{DOMxRef("RTCRtpTransceiver")}} objects
    being used to send and receive data on the connection.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.removeTrack", "removeTrack()")}}</dt>
  <dd>
    Tells the local end of the connection
    to stop sending media from the specified track,
    without actually removing the corresponding {{DOMxRef("RTCRtpSender")}}
    from the list of senders
    as reported by {{DOMxRef("RTCPeerConnection.getSenders", "getSenders()")}}.
    If the track is already stopped,
    or is not in the connection's senders list,
    this method has no effect.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.restartIce", "restartIce()")}}</dt>
  <dd>
    Allows to easily request
    that ICE candidate gathering be redone
    on both ends of the connection.
    This simplifies the process
    by allowing the same method
    to be used by either the caller or the receiver to trigger an {{Glossary("ICE")}} restart.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.setConfiguration", "setConfiguration()")}}</dt>
  <dd>
    Sets the current configuration of the connection
    based on the values included in the specified {{DOMxRef("RTCConfiguration")}} object.
    This lets you change the {{Glossary("ICE")}} servers
    used by the connection
    and which transport policies to use.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.setIdentityProvider", "setIdentityProvider()")}}</dt>
  <dd>
    Sets the Identity Provider (IdP) to the triplet given in parameter:
    its name, the protocol used to communicate with it and an username.
    The protocol and the username are optional.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.setLocalDescription", "setLocalDescription()")}}</dt>
  <dd>
    Changes the local description associated with the connection.
    This description specifies the properties of the local end of the connection,
    including the media format.
    It returns a {{jsxref("Promise")}}
    which is fulfilled
    once the description has been changed, asynchronously.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.setRemoteDescription", "setRemoteDescription()")}}</dt>
  <dd>
    Sets the specified session description
    as the remote peer's current offer or answer.
    The description specifies the properties of the remote end of the connection,
    including the media format.
    It returns a {{jsxref("Promise")}}
    which is fulfilled
    once the description has been changed, asynchronously.
  </dd>
</dl>

<h3 id="Obsolete_methods">Obsolete methods</h3>

<dl>
  <dt>{{DOMxRef("RTCPeerConnection.addStream", "addStream()")}} {{Obsolete_Inline}}</dt>
  <dd>
    Adds a {{DOMxRef("MediaStream")}} as a local source of audio or video.<br>
    Instead of using this obsolete method,
    you should instead use {{DOMxRef("RTCPeerConnection.addTrack", "addTrack()")}}
    once for each track
    you wish to send to the remote peer.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.createDTMFSender", "createDTMFSender()")}} {{Obsolete_Inline}}</dt>
  <dd>
    Creates a new {{DOMxRef("RTCDTMFSender")}},
    associated to a specific {{DOMxRef("MediaStreamTrack")}},
    that will be able to send {{Glossary("DTMF")}} phone signaling over the connection.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.getStreamById", "getStreamById()")}} {{Obsolete_Inline}}</dt>
  <dd>
    Returns the {{DOMxRef("MediaStream")}} with the given id
    that is associated with local or remote end of the connection.<br>
    This property has been replaced
    with the {{DOMxRef("RTCPeerConnection.getSenders", "getSenders()")}}
    and {{DOMxRef("RTCPeerConnection.getReceivers", "getReceivers()")}} methods.
  </dd>

  <dt>{{DOMxRef("RTCPeerConnection.removeStream", "removeStream()")}} {{Obsolete_Inline}}</dt>
  <dd>
    Removes a {{DOMxRef("MediaStream")}} as a local source of audio or video.
    Because this method is obsolete,
    you should instead use {{DOMxRef("RTCPeerConnection.removeTrack", "removeTrack()")}}.
  </dd>

</dl>

<h2 id="Events">Events</h2>

<p>Listen to these events using {{domxref("EventTarget.addEventListener", "addEventListener()")}} or by assigning an event listener to the <code>on<em>eventname</em></code> property of this interface.</p>

<dl>
  <dt>{{domxref("RTCPeerConnection.connectionstatechange_event", "connectionstatechange")}}</dt>
  <dd>
    Sent when the overall connectivity status of the <code>RTCPeerConnection</code> changes.<br>
    Also available through the {{domxref("RTCPeerConnection.onconnectionstatechange", "onconnectionstatechange")}} event handler property.
  </dd>

  <dt>{{domxref("RTCPeerConnection.datachannel_event", "datachannel")}}</dt>
  <dd>
    Sent when the remote peer adds an {{domxref("RTCDataChannel")}} to the connection.<br>
    Also available through the {{domxref("RTCPeerConnection.ondatachannel", "ondatachannel")}} event handler property.
  </dd>

  <dt>{{domxref("RTCPeerConnection.icecandidate_event", "icecandidate")}}</dt>
  <dd>
    Sent to request that the specified candidate be transmitted to the remote peer.<br>
    Also available through the {{domxref("RTCPeerConnection.onicecandidate", "onicecandidate")}} event handler property.
  </dd>

  <dt>{{domxref("RTCPeerConnection.icecandidateerror_event", "icecandidateerror")}}</dt>
  <dd>
    Sent to the connection if an error occurred during {{Glossary("ICE")}} candidate gathering. The event describes the error.<br>
    Also available through the {{domxref("RTCPeerConnection.onicecandidateerror", "onicecandidateerror")}} event handler property.
  </dd>

  <dt>{{domxref("RTCPeerConnection.iceconnectionstatechange_event", "iceconnectionstatechange")}}</dt>
  <dd>
    Sent when the state of the {{Glossary("ICE")}} connection changes, such as when it disconnects.<br>
    Also available using the {{domxref("RTCPeerConnection.oniceconnectionstatechange", "oniceconnectionstatechange")}} event handler property.
  </dd>

  <dt>{{domxref("RTCPeerConnection.icegatheringstatechange_event", "icegatheringstatechange")}}</dt>
  <dd>
    Sent when the {{Glossary("ICE")}} layer's gathering state, reflected by {{domxref("RTCPeerConnection.iceGatheringState", "iceGatheringState")}}, changes.
    This indicates whether ICE negotiation has not yet begun (<code>new</code>),
    has begun gathering candidates (<code>gathering</code>),
    or has completed (<code>complete</code>).<br>
    Also available using the {{domxref("RTCPeerConnection.onicegatheringstatechange", "onicegatheringstatechange")}} event handler property.
  </dd>

  <dt>{{domxref("RTCPeerConnection.negotiationneeded_event", "negotiationneeded")}}</dt>
  <dd>
    Sent when negotiation or renegotiation of the {{Glossary("ICE")}} connection needs to be performed;
    this can happen both when first opening a connection
    as well as when it is necessary to adapt to changing network conditions.
    The receiver should respond by creating an offer and sending it to the other peer.<br>
    Also available as the {{domxref("RTCPeerConnection.onnegotiationneeded", "onnegotiationneeded")}} event handler property.
  </dd>

  <dt>{{domxref("RTCPeerConnection.signalingstatechange_event", "signalingstatechange")}}</dt>
  <dd>
    Sent when the connection's {{Glossary("ICE")}} signaling state changes.<br>
    Also available through the {{domxref("RTCPeerConnection.onsignalingstatechange", "onsignalingstatechange")}} event handler property.
  </dd>

  <dt>{{domxref("RTCPeerConnection.track_event", "track")}}</dt>
  <dd>
    Sent after a new track has been added
    to one of the {{domxref("RTCRtpReceiver")}} instances which comprise the connection.<br>
    Also available as the {{domxref("RTCPeerConnection.ontrack", "ontrack")}} event handler property.
  </dd>
</dl>

<h3 id="Obsolete_events">Obsolete events</h3>

<dl>
  <dt>{{domxref("RTCPeerConnection.addstream_event", "addstream")}} {{Obsolete_Inline}}</dt>
  <dd>
    Sent when a new {{domxref("MediaStream")}} has been added to the connection.
    Instead of listening for this obsolete event,
    you should listen for {{domxref("RTCPeerConnection.track_event", "track")}} events;
    one is sent for each {{domxref("MediaStreamTrack")}} added to the connection.<br>
    Also available as the {{domxref("RTCPeerConnection.onaddstream", "onaddstream")}} event handler property.
  </dd>

  <dt>{{domxref("RTCPeerConnection.removestream_event", "removestream")}} {{Obsolete_Inline}}</dt>
  <dd>
    Sent when a {{domxref("MediaStream")}} is removed from the connection.
    Instead of listening for this obsolete event,
    you should listen for {{domxref("MediaStream.removetrack_event", "removetrack")}} events on each stream.<br>
    Also available as the {{domxref("RTCPeerConnection.onremovestream", "onremovestream")}} event handler property.
  </dd>
</dl>

<h2 id="Specifications">Specifications</h2>

{{Specifications}}

<h2 id="Browser_compatibility">Browser compatibility</h2>

<p>{{Compat}}</p>

<h2 id="See_also">See also</h2>

<ul>
 <li><a href="https://github.com/jesup/nightly-gupshup/blob/master/static/js/chat.js">https://github.com/jesup/nightly-gupshup/blob/master/static/js/chat.js</a></li>
 <li><a href="https://www.html5rocks.com/en/tutorials/webrtc/basics/#toc-simple">http://www.html5rocks.com/en/tutorials/webrtc/basics/#toc-simple</a></li>
 <li><a href="https://github.com/chrisjohndigital/TutorRoom">TutorRoom</a>: Node.js HTML5 video capture, peer-to-peer video and filesharing application (<a href="https://github.com/chrisjohndigital/TutorRoom">source on GitHub</a>)</li>
</ul>
