---
title: MediaKeySession.load()
slug: Web/API/MediaKeySession/load
tags:
- API
- EncryptedMediaExtensions
- Experimental
- MediaKeySession
- Method
- NeedsExample
- Reference
- load
browser-compat: api.MediaKeySession.load
---
<p>{{APIRef("EncryptedMediaExtensions")}}</p>

<p>The <code>MediaKeySession.load()</code> method returns a {{jsxref('Promise')}} that
  resolves to a boolean value after loading data for a specified session object.</p>

<h2 id="Syntax">Syntax</h2>

<pre
  class="brush: js"><var>mediaKeySession</var>.load(<var>sessionId</var>).then(function(<var>booleanValue</var>) { ... });</pre>

<h3 id="Parameter">Parameter</h3>

<dl>
  <dt>sessionId</dt>
  <dd>A unique string generated by the content description module for the current media
    object and its associated keys or licenses.</dd>
</dl>

<h3 id="Return_value">Return value</h3>

<p>A {{jsxref('Promise')}} that resolves to a boolean indicating whether the load
  succeeded or failed.</p>

<h2 id="Specifications">Specifications</h2>

{{Specifications}}

<h2 id="Browser_compatibility">Browser compatibility</h2>

<p>{{Compat}}</p>
