#!/usr/bin/env sh

# This script stores the 'main' branch's HEAD commit hash in .husky/_/history
# The stored commit hash is used by the post-merge script .husky/post-merge

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [ "$BRANCH" = "main" -a -d "./.husky/_" ]; then
  echo $(git rev-parse HEAD) > ./.husky/_/history
fi
