name: "Mark issues and pull requests as idle"
on:
  schedule:
    - cron: "49 11,23 * * *"

permissions:
  # Label issues.
  issues: write
  # Label pull requests.
  pull-requests: write

jobs:
  idle:
    uses: mdn/workflows/.github/workflows/idle.yml@main
    with:
      target-repo: "mdn/content"
