name: "Lock old issues and pull requests"
on:
  schedule:
    - cron: "0 9 1 * *"

jobs:
  lock:
    uses: mdn/workflows/.github/workflows/lock-closed.yml@main
    with:
      target-repo: "mdn/content"
