name: Check cSpell lists

on:
  pull_request:
    paths:
      - .vscode/dictionaries/*

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .vscode/dictionaries/*
            .nvmrc
            package.json
            package-lock.json
            scripts/sort_and_unique_file_lines.js
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"

      - name: Check if cSpell word lists are in correct order
        run: |
          node scripts/sort_and_unique_file_lines.js --check .vscode/dictionaries
