name: Check URL issues

on:
  pull_request:
    paths:
      - .github/workflows/pr-check_url-issues.yml
      - .nvmrc
      - package.json
      - package-lock.json
      - "files/**/*.md"
      - scripts/log-url-issues.js

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  check_url_issues:
    #if: github.repository == 'mdn/content'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Check URL deletions and broken fragments
        run: |
          echo "::add-matcher::.github/workflows/url-issues-problem-matcher.json"
          git fetch origin main
          node scripts/log-url-issues.js --workflow
