name: JSON lint

on:
  pull_request:
    paths:
      - .github/workflows/pr-check_json.yml
      - .nvmrc
      - "*.json"
      - "*.jsonc"
      - "**/*.json"
      - "**/*.jsonc"

# No GITHUB_TOKEN permissions, as we only use it to increase API limit.
permissions: {}

jobs:
  lint-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Install
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint JSON files
        run: npm run lint:json
