name: Label PRs by size

on:
  pull_request:
    branches:
      - "main"

jobs:
  # Docs: https://github.com/cbrgm/pr-size-labeler-action
  label-by-size:
    # do not run on forks
    if: github.repository == 'mdn/content'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Label PR based on size
        uses: cbrgm/pr-size-labeler-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ github.repository }} # Repository name
          github_pr_number: ${{ github.event.number }} # Pull request number
          config_file_path: ".github/pr-labels-by-size.yml" # Path to pr-size-labeler config
